# Generated by Django 3.1.4 on 2021-02-19 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verifyApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infouser',
            name='image',
        ),
    ]
