# Generated by Django 3.1.4 on 2021-02-20 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifyApp', '0003_auto_20210219_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infouser',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
