# Generated by Django 3.1.4 on 2021-02-20 06:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('verifyApp', '0005_auto_20210220_0354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infouser',
            name='image',
        ),
        migrations.AddField(
            model_name='infouser',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='profile_picture'),
        ),
        migrations.AlterField(
            model_name='infouser',
            name='name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='infouser',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
