# Generated by Django 3.1.4 on 2021-02-20 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifyApp', '0006_auto_20210220_0631'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infouser',
            old_name='person',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='infouser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_picture'),
        ),
    ]
