# Generated by Django 3.1.4 on 2021-02-21 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifyApp', '0007_auto_20210220_0641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infouser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='def.jpg', null=True, upload_to='profile_picture'),
        ),
    ]
